service: message-board

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-dynamodb-local
  - serverless-offline-sns
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      dbPath: .dynamodb

  serverless-offline-sns:
    port: 4002
    debug: false
    location: .build

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello
          method: get
          cors: true

  registerUser:
    handler: handler.registerUser
    events:
      - http:
          path: register
          method: post
          cors: true

  getUserByEmail:
    handler: handler.getUserByEmail
    events:
      - http:
          path: user
          method: get
          cors: true

  saveUserToDynamoDB:
    handler: handler.saveUserToDynamoDB
    events:
      - sns:
          arn: !Ref UserRegistrationTopic
          topicName: UserRegistrationTopic

resources:
  Resources:
    UserRegistrationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: UserRegistrationTopic

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
